# Linker Settings can apply to all crates in project vs modifying just the build.rs file in lib/api

[build]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]

[target.x86_64-unknown-linux-gnu]  # Replace with your target triple
linker = "clang"
